export enum Estado {
  PENDIENTE   = 'PENDIENTE',
  CONFIRMADO = 'CONFIRMADO',
  EN_PREPARACION = 'EN_PREPARACION',
  DEMORADO = 'DEMORADO',
  LISTO = 'LISTO',
  RECHAZADO   = 'RECHAZADO',
  EN_CAMINO = "EN_CAMINO",
  ENTREGADO   = 'ENTREGADO'
}